### ISSUE TITLE
add !tshock.ignore.ssc to Vanillafied groups

### ISSUE THREAD

**Issue by Menchen** [Pryaxis/Vanillafier#1]
By default this plugin add `tshock.ignore.*` that include `tshock.ignore.ssc` and disable ssc of all players.

**Comment by QuiCM** [comment]
Good catch. Will fix

**Comment by QuiCM** [comment]
@Menchen thanks for the report. I have added !tshock.ignore.ssc to the Vanillafied permission set

**Comment by Menchen** [comment]
I just found out that player are unable to register and login(you need that for ssc)
So
tshock.account.*
Is needed..

**Comment by QuiCM** [comment]
Thanks, I've added tshock.account.* now :)
